name: test
on: [push, pull_request]
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
